version: '2'
services:
  webserver:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 9080:80
    expose: [9001]
    environment:
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
      XDEBUG_CONFIG: remote_host=10.254.254.254
